# Generated by Django 3.2 on 2021-05-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/%Y%m', verbose_name='用户头像')),
                ('nickname', models.CharField(max_length=32, unique=True, verbose_name='昵称')),
            ],
            options={
                'db_table': 'account_user',
            },
        ),
    ]
