# Generated by Django 3.2 on 2021-05-11 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sight', '0002_comment_info_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='sight.sight', verbose_name='景点门票'),
            preserve_default=False,
        ),
    ]
